apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nodjs-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata: 
      name: Nodejs-Pods
      labels:
        env: prod 
    spec:
      containers:
      - name: nodejscontainers
        image: abdulfattahassad/nodejs-docker
        ports:
        - containerPort: 3000
        
---


apiVersion: v1 
kind: Service 
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer 
  selectors:
    env: prod 
ports:
  - port: 3000
    targetPort: 3000
    nodePort: 3000

